name: owner_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6

  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  intl: ^0.18.1
  crypto: ^3.0.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  uuid: ^4.1.0
  place_picker:
  geolocator:
  geocoding: ^2.1.1
  geoflutterfire2: ^2.3.15
  dotted_border: ^2.1.0
  flutter_share: ^2.0.0
  lottie: ^2.6.0
  syncfusion_flutter_datepicker: ^23.1.40
  url_launcher: ^6.1.14
  flutter_email_sender: ^6.0.2


  #firebase_dependencies
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  flutter_local_notifications: ^16.1.0
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

  flutter:
    sdk: flutter

dependency_overrides:
  location: ^5.0.3



dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
    - assets/fonts/



  fonts:
    - family: Figtree-Regular
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf

    - family: Figtree-Medium
      fonts:
        - asset: assets/fonts/Figtree-Medium.ttf

    - family: Figtree-Bold
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf

    - family: Figtree-SemiBold
      fonts:
        - asset: assets/fonts/Figtree-SemiBold.ttf
