// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXA7vkMfJ5QwcrgQmle35CSXrKr5Tgf20',
    appId: '1:380287931734:android:3dd5c2eb21352c93be72f7',
    messagingSenderId: '380287931734',
    projectId: 'spot-a-park-app',
    storageBucket: 'spot-a-park-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Yr4fmUbpHpAiLgZi8bAN90DnWQbfo4o',
    appId: '1:380287931734:ios:02d8bc61777354dabe72f7',
    messagingSenderId: '380287931734',
    projectId: 'spot-a-park-app',
    storageBucket: 'spot-a-park-app.appspot.com',
    androidClientId: '380287931734-0ne2n7v0k8fnpbjcer1g5tgmulasvhlo.apps.googleusercontent.com',
    iosClientId: '380287931734-ba71kndcsacp3c6u1gd7r0a3ce8euvd8.apps.googleusercontent.com',
    iosBundleId: 'com.sataware.spotapark-owner',
  );

}